server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: miaosha-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/le-cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 20190814zw
    hikari:
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 200
      # 最小空闲连接数
      minimum-idle: 20
      # 连接池用完后，申请新连接的等待时间，超出此时间则抛出异常
      connection-timeout: 30000
  redis:
    redisson:
      address: redis://localhost:6379
      password: redis20190715***
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryInterval: 3000
      nettyThreads: 128

rocketmq:
  namesrv: localhost:8201;localhost:8202
  producer:
    retryTimesWhenSendFailed: 3
  order:
    group: miaosha-backend
    topic: seckill-order

mb:
  # 秒杀流量每秒限制
  limiter-permits: 100